[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "fonts-liberation"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma db push",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
